name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Generate coverage report
      run: go test -coverprofile=coverage.out ./...

    - name: Check coverage
      id: coverage
      run: |
        coverage=$(go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
        echo "total_coverage=$coverage" >> $GITHUB_OUTPUT
        echo "Coverage: $coverage%"

    - name: Fail if coverage is below threshold
      run: |
        if (( $(echo "${{ steps.coverage.outputs.total_coverage }} < 100" | bc -l) )); then
          echo "Coverage (${{ steps.coverage.outputs.total_coverage }}%) is below the threshold (100%)"
          exit 1
        fi
